from .base_prompts import SEARCH_PROMPT, TARGET_OBJECT, TARGET_DISTANCE, DISTANCE_TOLERANCE
from .tracking_prompts import get_tracking_prompt
from .attitude_prompts import get_attitude_tracking_prompt