# The robot description defines the generalized coordinates and how to map those
# to the underlying URDF dofs.

api_version: 1.0

cspace:
    - arm_sh0
    - arm_sh1
    - arm_el0
    - arm_el1
    - arm_wr0
    - arm_wr1
default_q: [
    0.0,1e-04,1e-04,-0.0,0.0029,-0.0
]

acceleration_limits: [
   10,10,10,10,10,10
]

jerk_limits: [
   10000,10000,10000,10000,10000,10000
]

base_link: body

cspace_to_urdf_rules:
    - {name: fl_hx, rule: fixed, value: 0.0003}
    - {name: fr_hx, rule: fixed, value: -0.0003}
    - {name: hl_hx, rule: fixed, value: 0.0003}
    - {name: hr_hx, rule: fixed, value: -0.0003}
    - {name: fl_hy, rule: fixed, value: -0.0}
    - {name: fr_hy, rule: fixed, value: -0.0}
    - {name: hl_hy, rule: fixed, value: -0.0}
    - {name: hr_hy, rule: fixed, value: -0.0}
    - {name: fl_kn, rule: fixed, value: -0.2471}
    - {name: fr_kn, rule: fixed, value: -0.2471}
    - {name: hl_kn, rule: fixed, value: -0.2471}
    - {name: hr_kn, rule: fixed, value: -0.2471}
    - {name: arm_f1x, rule: fixed, value: 0.0}

collision_spheres:
  - arm_link_sh0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.06
  - arm_link_sh1:
        - "center": [0.05, 0.0, 0.0]
          "radius": 0.06
        - "center": [0.15, 0.0, 0.0]
          "radius": 0.055
        - "center": [0.25, 0.0, 0.0]
          "radius": 0.055
        - "center": [0.33, 0.0, 0.0] # Near Elbow
          "radius": 0.06
  - arm_link_el0:
        - "center": [0.05, 0.0, 0.0]
          "radius": 0.055
        - "center": [0.15, 0.0, 0.0]
          "radius": 0.05
        - "center": [0.25, 0.0, 0.0]
          "radius": 0.05
        - "center": [0.35, 0.0, 0.0]
          "radius": 0.05
        - "center": [0.40, 0.0, 0.0] # Near Wrist
          "radius": 0.055
  - arm_link_wr0:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.04
  - arm_link_wr1:
        - "center": [0.0, 0.0, 0.0]
          "radius": 0.04
        - "center": [0.06, 0.0, 0.0]
          "radius": 0.035
  - arm_link_fngr:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.01
